export const PAYMENT_REQUEST = "PAYMENT_REQUEST";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAIL = "PAYMENT_FAIL";
export const PAYMENT_RESET = "PAYMENT_RESET";
export const PAYMENT_AUTHORIZATION_REQUEST = "PAYMENT_AUTHORIZATION_REQUEST";
export const PAYMENT_AUTHORIZATION_SUCCESS = "PAYMENT_AUTHORIZATION_SUCCESS";
export const PAYMENT_AUTHORIZATION_FAIL = "PAYMENT_AUTHORIZATION_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
